minor changes to destroy-cloudformation-stack-on-dispatch.yml

diff --git a/.github/workflows/destroy-cloudformation-stack-on-dispatch.yml b/.github/workflows/destroy-cloudformation-stack-on-dispatch.yml
--- a/.github/workflows/destroy-cloudformation-stack-on-dispatch.yml
+++ b/.github/workflows/destroy-cloudformation-stack-on-dispatch.yml
@@ -3,16 +3,23 @@ on:
   workflow_dispatch:
 jobs:
   destroy:
-    name: Destroy CloudFormation Stack
+    name: Destroy CloudFormation stack
     runs-on: ubuntu-latest
     steps:
-      - name: Configure AWS Credentials
+      - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v3
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
-      - name: Delete Stack
+      - name: Check CloudFormation stack exists
+        run: |
+          set -e
+          if ! aws cloudformation describe-stacks --stack-name ${{ vars.CLOUDFORMATION_STACK_NAME }} >/dev/null 2>&1; then
+            echo "Error: Stack ${{ vars.CLOUDFORMATION_STACK_NAME }} does not exist."
+            exit 1
+          fi
+      - name: Delete CloudFormation stack
         run: |
           aws cloudformation delete-stack \
             --stack-name ${{ vars.CLOUDFORMATION_STACK_NAME }}
